name: PHP CI

on:
  push:
    branches: [main, master]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          coverage: none

      - name: Install dependencies
        run: composer install

      - name: Lint with PHP-CS-Fixer
        run: |
          composer global require friendsofphp/php-cs-fixer
          php-cs-fixer fix --dry-run --diff --ansi

      - name: Run PHPUnit
        run: ./vendor/bin/phpunit
