name: PHP CI

on:
  push:
    branches: [main, master]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          coverage: none

      - name: Install dependencies
        run: composer install

      - name: Run PHPUnit
        run: ./vendor/bin/phpunit
