name: PHP_CodeSniffer

on:
  push:
    branches:
      - main

jobs:
  phpcs:
    name: Run PHP_CodeSniffer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          extensions: mbstring, intl, json, redis
          coverage: none

            - name: Install dependencies
              run: |
                    composer install --prefer-dist --no-progress
                    composer global require "squizlabs/php_codesniffer=*"


      -       - name: Run PHP_CodeSniffer
        run: ~/.composer/vendor/bin/phpcs --standard=PSR1,PSR2 src/C:\Users\tomde\OneDrive\Documents\One drive\OneDrive\Cours_de_L2\Qualité de code\TD06\exo.php


